name: deploy-marketing

on:
  push:
    branches:
      - master
    paths:
      - "packages/marketing/**"

defaults:
  run:
    working-directory: packages/marketing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
      - name: Build the marketing package
        run: npm run build
